### PR TITLE
Add Python 3 support + PEP8 + setup.py classifiers

### PR DESCRIPTION
**Pull request by GMLudo**
Hi,

This PR adds Python 3 support and keeps Python 2 compatibility.

If you might release a new version on PyPI, it should be awesome ;-)

Have a nice week.

### CODE REVIEW

**Comment by GMLudo** [comment]
Gentle ping ;-)

**Comment by rdegges** [comment]
This is awesome! Thank you. Will update soon =D

**Comment by rdegges** [comment]
Released `0.4.0` just now on PYPI. Thanks again =)

**Comment by GMLudo** [comment]
Thanks a lot :-)

**Comment by GMLudo** [comment]
Hi @rdegges,

On PyPI, it seems to be still 0.3 and not 0.4.0: https://pypi.python.org/pypi/basicauth
Could you publish again ?

Thank you.

**Comment by GMLudo** [comment]
Gentle ping ;-)

**Comment by rdegges** [comment]
Gaahhh. Finally got this done! Thanks for the reminders. Work is crazy.

**Comment by GMLudo** [comment]
> Work is crazy.

Don't worry, same here.
It works as expected.
It's important to us to be the closest as possible of the upstream, to have more users than ourselves for our patches.

Have a nice week-end.

**Pull request merged**
